// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyuanxeexbdnpcuznmgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dWFueGVleGJkbnBjdXpubWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODgyMjksImV4cCI6MjA2OTg2NDIyOX0.srXmGYu30qd8M4a7Q7vuK4d2DW_VHHSnF175Sg-D840";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});